# Setup
title:               Art Vivant Libre
description:         Appel aux artistes et organisateurs de spectacle vivant
url:                 https://artvivantlibre.github.io
baseurl:             artvivantlibre-site
permalink:           pretty

# About/contact
author:
  name:              Art Vivant Libre
  url:
  email:             artvivantlibre@protonmail.com

# Gems
#plugins:
  #- jekyll-paginate
